name: Pipeline principal
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: run tests backend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: | #Entra a carpeta Backend, instala dependencias y ejecuta tests
          cd Backend
          npm install
          npm run test
      - name: run tests frontend
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: | #Entra a carpeta Frontend, instala dependencias, levanta frontend y ejecuta tests
          cd frontend
          npm install
          npm start &
          npm run test:e2e
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3 #action para config y uso de codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #consumo de variable de nivel repositorio, dada por CodeCoverage
          fail_ci_if_error: true
          verbose: true

  build:
    needs: test #Depende de la etapa de test para continuar
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image Backend
        uses: docker/build-push-action@v2
        with:
          context: ./Backend/
          push: true
          dockerfile: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ayd1-backend:latest
          env: |
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASS=${{ secrets.DB_PASS }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_PORT=${{ secrets.DB_PORT }}
            API_PORT=${{ secrets.API_PORT }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
      - name: Build and push Docker image Frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/
          push: true
          dockerfile: ./Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ayd1-frontend:latest